name: Update README Progress

on:
  push:
    branches:
      - main
  schedule:
    - cron: "*/3 * * * *" # Runs every 3 minutes

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Count completed tasks
        id: count-tasks
        run: |
          # Count the number of '✅' in the second-to-last column (Status column)
          count=$(grep -oP '(?<=<td align="center">)✅(?=</td>)' README.md | wc -l)
          echo "TASK_COUNT=$count" >> $GITHUB_ENV

      - name: Update README with dynamic badge
        run: |
          # Inject the dynamic task count into a badge URL in the README
          sed -i "s|{{ ACHIEVED_TASKS }}|$TASK_COUNT|g" README.md

      - name: Commit and push changes
        run: |
          if ! git diff --exit-code README.md > /dev/null; then
            git config --global user.email "actions@github.com"
            git config --global user.name "Github Actions"
            git add README.md
            git commit -m "Update README with progress: $TASK_COUNT/150"
            git push
          fi
